### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by andyscott12** [Automattic/es-backbone#4]
Hey,

This is really awesome - are you still actively developing this or ? 

I'm learning elasticSearch and use BackboneJS a lot so was wondering whether I should start with this.

**Comment by gibrown** [comment]
Hi, we use this library internally for a number of searches, so do still keep it actively maintained. We have 150+ people who have been using it every day for quite a while now.

I haven't had the time to maintain the sample code that I originally provided, so you may find some differences (mostly improvements). Ideally I'd like to build some sample code that uses a real public API, but currently I don't have one that I can build against. Unfortunately doing that is kinda low on my list right now. Would be happy to integrate in any patches or bugs you find against either the main lib or the sample code.
