### ISSUE TITLE
Refresh on event: remove facet

### ISSUE THREAD

**Issue by po5i** [Automattic/es-backbone#5]
When I click on the X icon to remove a facet, the interface does not refresh as when I click on a new facet.

Where is the "refresh" command so I can invoke when the facet is removed?

**Comment by po5i** [comment]
Thinking of invoke $(".esbb-search-button").click();    after removing the facet.

**Comment by gibrown** [comment]
Is this in a esbbSearchFilterTermsSelectorView element or something else? In that View it works correctly via https://github.com/Automattic/es-backbone/blob/master/es-backbone.js#L941

Maybe you're using esbbSearchFilterSelectView which does not seem to do the same thing: https://github.com/Automattic/es-backbone/blob/master/es-backbone.js#L799

You could try adding t.model.search(); and I think that will work. If it does submit a pull request and I'll integrate it in.

**Comment by po5i** [comment]
It works just adding what you said.

Today I made a fork and I will use a self public index, get back to you with the details soon
